--- #YAML:1.0
name:                File-FcntlLock
version:             0.11
abstract:            File locking with L<fcntl(2)>
license:             ~
author:              
    - Jens Thoms Toerring <jt@toerring.de>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    DynaLoader:                    0
    Errno:                         0
    Exporter:                      0
    POSIX:                         0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
