--- #YAML:1.0
name:               File-FcntlLock
version:            0.13
abstract:           File locking with L<fcntl(2)>
author:
    - Jens Thoms Toerring <jt@toerring.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:        0
    DynaLoader:  0
    Errno:       0
    Exporter:    0
    POSIX:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
